services:
  redis:
    image: redis:8.2.1
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - data_redis:/data
  postgres:
    image: postgres:17.6
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
      - data_postgres:/var/lib/postgresql/data
  mc1:
    image: itzg/minecraft-server:latest
    container_name: mc1
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.4
      MEMORY: 2G
      ONLINE_MODE: "FALSE"
      SYNC_SKIP_NEWER_IN_DESTINATION: false
    volumes:
      - data_mc1:/data
      - ./paper-global.yml:/config/paper-global.yml:ro
    depends_on:
      - redis
      - postgres
  mc2:
    image: itzg/minecraft-server:latest
    container_name: mc2
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.4
      ONLINE_MODE: "FALSE"
      SYNC_SKIP_NEWER_IN_DESTINATION: false
    volumes:
      - data_mc2:/data
      - ./paper-global.yml:/config/paper-global.yml:ro
    depends_on:
      - redis
      - postgres
  mc3:
    image: itzg/minecraft-server:latest
    container_name: mc3
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.21.4
      ONLINE_MODE: "FALSE"
      SYNC_SKIP_NEWER_IN_DESTINATION: false
    volumes:
      - data_mc3:/data
      - ./paper-global.yml:/config/paper-global.yml:ro
    depends_on:
      - redis
      - postgres
  velocity:
    image: itzg/mc-proxy
    environment:
      TYPE: VELOCITY
      DEBUG: "false"
      ENABLE_RCON: "true"
    ports:
      - "25565:25577"
    volumes:
      - ./velocity.toml:/config/velocity.toml:ro
      - ./forwarding.secret:/config/forwarding.secret:ro
    depends_on:
      - mc1
      - mc2

volumes:
  data_redis:
  data_postgres:
  data_mc1:
  data_mc2:
  data_mc3: